### ISSUE TITLE
Japanese city names in romaji 

### ISSUE THREAD

**Issue by easternWolf9222** [polm/cutlet#36]
Why are city names like 東京 and 大阪 converted to Tokyo and Osaka instead of Toukyou and Oosaka? I am working on a text-to-speech project and it caused the program to pronounce them incorrectly.

**Comment by polm** [comment]
This happens because of the [exceptions list](https://github.com/polm/cutlet/blob/master/cutlet/exceptions.tsv). The README mentions this right at the top with those two specific examples. 

![2023-08-26T23-58-16](https://github.com/polm/cutlet/assets/286278/59c1dd3c-4a4d-4317-85bb-673c9d368e11)

Those two are in the exception list because those are the conventional romanizations of those city names. If you want to disable the behavior, you can just blank the exceptions list. 

```
cut = cutlet.Cutlet()
cut.exceptions = {}
cut.romaji("東京と大阪")
# => Toukyou to Oosaka
```

**Comment by easternWolf9222** [comment]
Ahh I see! That's a dumb question. Thank you for the amazing tool.
