### ISSUE TITLE
Strange Conversion

### ISSUE THREAD

**Issue by lobochrome** [polm/cutlet#53]
グロ－バルウイザ

Which is some sort of company name as returned by Yuchou Ginkou is transcribed as 

grotesque - baru oui the

That is a very very strange result in my opinion. I wouldn't for the life of me get there from reading the katakana alone.

**Comment by lobochrome** [comment]
So the company name is "Global With Us" - but of course - I have no idea how their banking name is officially and the "su" seems to be cut off. But still - how does it lead to "grotesque - baru oui the" ???

**Comment by polm** [comment]
The long vowel mark is using a nonstandard character (minus sign), so it is not interpreted as part of any word. The rest of the strange conversion just follows from that.

**Comment by lobochrome** [comment]
Maybe I misunderstood how the tool works then - I wouldn't expect it to expand "グロ" to "grotesque" but would expect only "guro." To me, it seems rather aggressive to forward-guess this much.

**Comment by lobochrome** [comment]
Okay - I dug into the db and extracted the raw string. Of course it's beautiful half-width Katakana - don't we love them all:

振込 ｶ)ｸﾞﾛ-ﾊﾞﾙｳｲｻﾞ

Maybe an edge case to consider. Maybe not.

**Comment by polm** [comment]
Half-width katakana has a long vowel mark which is distinct from the hyphen: ｸﾞﾛｰﾊﾞﾙ can be converted to "Global" without issue.

It looks like you have a bank record. I looked into whether not using the long vowel mark is a restriction of 全銀, and while I have trouble finding an authoritative source, it does seem that 全銀 requires use of the minus symbol. In that case you can do a mass replace. Since this is not a general limitation of half-width katakana, I am not comfortable making it default behavior. 

For "guro", no guessing is being done - cutlet just reflects what is in UniDic, which is based on etymology, not orthography. In this case it's certainly a bit surprising, so it's a good candidate for an exception.

**Comment by polm** [comment]
Closing because while this was unfortunate, I don't think there's anything to do here that wouldn't have other knock-on effects. Please feel free to followup if you feel otherwise.

**Comment by lobochrome** [comment]
Thanks for your hard work. Fully agreed. Still considering what to do but honestly in years this was the only really strange result so I'll let it run as is.
